
IMAGE_HEIGHT = 64
IMAGE_WIDTH = 64
N_CHANNEL = 3
INPUT_DIM = (IMAGE_HEIGHT, IMAGE_WIDTH, N_CHANNEL)

MAX_SPEED = 0.6
MIN_SPEED = 0.4

MAX_STEERING_DIFF = 0.15
MAX_STEERING = 1
MIN_STEERING = -1

REWARD_CRASH = -10 #negative number.


CRASH_SPEED_WEIGHT = 0.1
THROTTLE_REWARD_WEIGHT = 0.1
JERK_REWARD_WEIGHT = 0.0
